### ISSUE TITLE
Armor miscalculated

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#332] opened 2017-07-20 04:34 UTC
I haven't tried to replicate this, but I was wearing an iron chestplate, leather leggins and diamond boots. My boots broke and my armor actually went up instead of down. From 6 shields to 8, if I remember correctly.

**Comment by Wuzzy2** [comment] 2017-07-20 14:05
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/249.

**Closed by Wuzzy2** 2017-07-20 14:05 UTC
Labels: duplicate
