### ISSUE TITLE
Bugs 'n glitches in subgame version 0.10.0 

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#35] opened 2017-02-19 09:54 UTC
1. It's possible to pass bedrock floor and go deeper than y-64
![screenshot_20170219_112155](https://cloud.githubusercontent.com/assets/13905392/23101214/e8bfbf04-f696-11e6-8cd5-376dbed95a12.png)

2. Bow almost useless, it requires on arrows on hotbar attached like this:
![screenshot_20170219_114109](https://cloud.githubusercontent.com/assets/13905392/23101279/82fd28d0-f698-11e6-9466-3473763b2d95.png)
Not good, bad durability: 9 shots (sometimes).
Unreloaded bow: No shooting.
Reloaded bow on low charge: shooting on low speed.
Reloaded bow on medium charge: shooting on medium speed.
Reloaded bow on maximum charge: shooting on maximum speed + 50% chance for critical hit.
There is no way to cancel charging bow if it's not selected or storing on chest.

3. Fishing rod is unbreakable or OP and it has a chance to get unknown item by catching with left-click on water source.

4. Others
![screenshot_20170219_113449](https://cloud.githubusercontent.com/assets/13905392/23101316/5e7678a8-f699-11e6-8ada-7f266638482f.png)
Placing torches don't make sound. Activating pistons don't make sound. Pressure plates don't make sound. Dispensers and droppers don't make sound. Player damage don't make sound. There is more...

**Comment by WSDguy2014** [comment] 2017-02-19 09:58
There is no Moon phases?

**Comment by WSDguy2014** [comment] 2017-02-19 10:01
I have to ask a question @Wuzzy2: Why you not using Minecraft sounds? Are you trying to avoid sounds stuff?

**Comment by WSDguy2014** [comment] 2017-02-19 10:04
I'm trying to tame a wolf with bones, but i can't.

**Comment by WSDguy2014** [comment] 2017-02-19 10:07
It's difficult to sprint.

**Comment by WSDguy2014** [comment] 2017-02-19 10:21
I found a strange glitch on clock that turns into unknown node, because "mcl_clock:clock_64" is missing if it's on night time. And few seconds later, it turns back to normal.
![screenshot_20170219_121842](https://cloud.githubusercontent.com/assets/13905392/23101518/e356dc94-f69d-11e6-8cf0-db7c58f54ad7.png)

**Comment by WSDguy2014** [comment] 2017-02-19 17:17
I tried to rename mob with item "Name Tag" for example pig (needs to be only tamed), it crashes:
![image](https://cloud.githubusercontent.com/assets/13905392/23104505/de340a72-f6d7-11e6-8ae5-dffb39a06b91.png)

**Comment by WSDguy2014** [comment] 2017-02-19 17:31
Another glitch that i found. Make a large chest facing for example east, place 2 hoppers like this:
![screenshot_20170219_192158](https://cloud.githubusercontent.com/assets/13905392/23104567/02563c44-f6d9-11e6-9ba0-846cfd33f3de.png)

I drop 5 diamond blocks on left hopper:
![screenshot_20170219_192221](https://cloud.githubusercontent.com/assets/13905392/23104578/309a0694-f6d9-11e6-8b11-e7e2164441e9.png)

It works just normal.
![screenshot_20170219_192227](https://cloud.githubusercontent.com/assets/13905392/23104592/73870290-f6d9-11e6-810b-a72e220fec99.png)

I drop another 5 diamond blocks on right hopper:
![screenshot_20170219_192236](https://cloud.githubusercontent.com/assets/13905392/23104596/9784c02e-f6d9-11e6-94d4-b81863e9dc5a.png)

Incorrectly stores it.
![screenshot_20170219_192241](https://cloud.githubusercontent.com/assets/13905392/23104598/ae9d7936-f6d9-11e6-86a9-6c2e9830fafe.png)

**Comment by WSDguy2014** [comment] 2017-02-19 17:38
Green: left hopper only stores here.
Red: right hopper only stores here.
![screenshot_20170219_192241](https://cloud.githubusercontent.com/assets/13905392/23104664/f681bfae-f6da-11e6-8e63-5415b5f67619.png)

**Comment by WSDguy2014** [comment] 2017-02-19 17:45
Player shooting with arrow, arrow facing wrong way to the player:
![screenshot_20170219_194158](https://cloud.githubusercontent.com/assets/13905392/23104721/d6bc1e48-f6db-11e6-9238-b0d203f3bb7a.png)

**Comment by Wuzzy2** [comment] 2017-02-19 18:19
-Thanks for all the testing and stuff, BUT:
Aaaaargh!
Please stop posting everything in a single issue. Please file one issue per bug/missing feature. It is very hard for me to keep track of the bugs then.

I will only reply directly to TWO questions here:

> Why you not using Minecraft sounds? Are you trying to avoid sounds stuff?

I will avoid ANY original Minecraft data because it is copyright of Mojang AB and/or Microsoft (not sure). I want MineClone 2 to be 100% free software, no string attached. Proprietaty *anything* is an absolute no-go. That having said, all I need to do is find some good sounds in general and of course pistons and all the other things will have sounds, I just didn't add them so far.

Your other bug reports are legit and on my TODO list.

**Comment by Wuzzy2** [comment] 2017-02-19 20:21
> Fishing rod is unbreakable or OP and it has a chance to get unknown item by catching with left-click on water source.

Partially fixed in development version. Fishing rod is no longer unbreakable and doesn't get unknown items anymore. It also uses rightclick.

But yes, fishing rod is unfinished and overpowered since there is no delay. This is still a WIP.

> I tried to rename mob with item "Name Tag" for example pig (needs to be only tamed), it crashes:

Fixed in dev.

> I found a strange glitch on clock that turns into unknown node, because "mcl_clock:clock_64" is missing if it's on night time. And few seconds later, it turns back to normal.

Fixed in dev. Nice find.

> Placing torches don't make sound. Activating pistons don't make sound. Pressure plates don't make sound. Dispensers and droppers don't make sound. Player damage don't make sound. There is more...

Torches and pistons now have sounds in dev. Many other sounds are still TODO.

Unknown items in crafting recipes are because the items still have to be added. These recipes will start working as soon as I added the missing items. The recipes are correct.

> It's possible to pass bedrock floor and go deeper than y-64

Bedrock mapgen is VERY broken indeed. This is now on the high-priority TODO list.

**Comment by WSDguy2014** [comment] 2017-02-19 21:56
@Wuzzy2, how about old Minecraft sounds? I seen old texture for porkchop and cooked porkchop from mobs redo mod by TenPlus1.

**Comment by Wuzzy2** [comment] 2017-02-20 02:46
I will not take sounds, images or anything with the risk of being copyrighted / proprietary. This is not debatable.
Old Minecraft sounds are still unlikely to be exempt from this, unless you can proof they're actually public domain / released under a free license. I doubt it. Anyways, I will gladly take any suggestions to include sounds under a free license (including, but not limited to: CC BY, CC BY-SA, MIT, WTFPL, CC0, …) and it would be a huge help to me.

If you want to help me, you can post links to particular sounds and maybe a short note on for what it should be used. But don't
Possible sources of sounds are:

* https://www.freesound.org/
* Minecraft resource packs (but check the license first)
* Other Minetest mods

**Comment by WSDguy2014** [comment] 2017-02-20 14:29
In Minecraft, name tags are useful to make any mobs never despawn.

**Comment by Wuzzy2** [comment] 2017-02-20 14:47
From now on, please post a **new** issue per new bug or missing feature found instead of posting in this  huge issue. It's getting WAY out of hand now.

I'm closing this whole issue as invalid now. I have now created separate issues for each of your bug reports so far.

As closing remakrs:
* Bedrock generation: Fixed.
* Bow issues: Confirmed.
* Bad fishing rod: Confirmed, it's too overpowered indeed.
* Missing sounds: A few of them have been added, I will add more over time.
* Moon phases: Confirmed.
* Tame wolves with a bone: Fixed.
* Bad sprinting: Confirmed, sprinting is very very WIP.
* Missing clock item bug: Fixed.
* name tag crash: Fixed.
* Hoppers and large chests: Confirmed.
* Arrow facing bug: Confirmed.
* name tags for preventing despawn: Confirmed.

**Closed by Wuzzy2** 2017-02-20 14:47 UTC
Labels: bug
