### ISSUE TITLE
Dungeon spawners

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#361] opened 2017-08-07 09:57 UTC
In 0.26.0 I noticed that placing a torch on and/or around a dungeon spawner doesn't disable the spawns of a dungeon spawner. Usually when a torch is placed on or near a spawner, the light from the torch stops the spawner from spawning more mobs.

**Comment by leorockway** [comment] 2017-08-07 13:21
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/221

**Closed** 2017-08-07 14:05 UTC
Labels: duplicate
