### ISSUE TITLE
Unable to register node to be dug

### ISSUE THREAD

**Issue by maikerumine** [Wuzzy2/MineClone2-Bugs#312] opened 2017-06-30 17:56 UTC
This is a tricky one to explain.

When doing an override of a node e.g. :mcl_core:obsidian, this makes the node however it is unable to be dug.

Also, when refrencing mcl_tools as a depends, this locks out the node to be dug.

Both of these issues are chained into the autogroup script, for some reason.

I can give a better example here:

1.  make a new mod and register a node.
2.  in depends, depend on mcl_tools.
3.  spawn node in world and try to break.

also, do a simple:  minetest.register_node(":mcl_core:emeraldblock", {def}) and try to mine it.  to make sure you are using the overridden node, just change the description so you know it is active, else add a minetest_after command to register it later.

In both situations the node exists, can do internal functions, but cannot be dug.

Am I missing something in the way mc2 registers nodes?

**Comment by maikerumine** [comment] 2017-06-30 18:36
Also, torches cannot be placed on these "nodes" due to them not being nodes?  odd

**Comment by Wuzzy2** [comment] 2017-06-30 19:27
If you re-define any node like this, you **must** depend on the mod which contains the original node.

**Comment by Wuzzy2** [comment] 2017-07-06 14:39
If there will be no reply soon, I'll close this issue as I can't reproduce it and it works when you properly add dependencies.

**Closed** 2017-07-08 14:48 UTC
Labels: more information needed
