### ISSUE TITLE
Stone pick can mine diamond etc.

### ISSUE THREAD

**Issue by maikerumine** [Wuzzy2/MineClone2-Bugs#301] opened 2017-06-22 17:50 UTC
This should not drop a block as well as hand.  There could be function to not drop if tool used is weak.

**Comment by Wuzzy2** [comment] 2017-06-22 18:08
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/146.

**Closed by Wuzzy2** 2017-06-22 18:08 UTC
Labels: duplicate
