### ISSUE TITLE
cant place blocks in the same space as itemframes and paintings

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#439] opened 2017-11-30 00:18 UTC
cant place blocks in the same space as itemframes (becouse they count as bsolid blocks and not enteties)

a demo video
https://youtu.be/qfUinhMfkTI

wanna have some use cases of this just google minecraft item frame decoration ideas

**Comment by Wuzzy2** [comment] 2017-11-30 00:50
Duplicate of #42.

**Closed by Wuzzy2** 2017-11-30 00:50 UTC
Labels: duplicate
