### ISSUE TITLE
No damage from hostile cave spiders while wearing chain mail armor

### ISSUE THREAD

**Issue by dawgdoc** [Wuzzy2/MineClone2-Bugs#418] opened 2017-10-20 06:46 UTC
While playing in singleplayer survival world I seem to have found an issue with cave spiders not inflicting damage when made hostile by me attacking them. Running MT 0.4.16 stable on LinuxMint 18.2. MCL2 and mcl_supplemental are current as of 15 Oct. 

I found a cave spider spawner in a 'room' just off of an abandoned mine. I could not stop the spawner from spawning spiders no matter how many torches I placed ( already noted as issue #221 ), so I waded in and started hewing at them with my iron/steel sword. I was in there for over 2 minutes killing wave after wave of spawned spiders and took no damage to health or the chain-mail armor I was wearing. 

I found the issue regarding Leather armor and Endermen #285 but thought this may be different.

**Comment by Wuzzy2** [comment] 2017-10-21 19:16
This is because of armor being generally balanced poorly.

Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/243.

**Closed by Wuzzy2** 2017-10-21 19:16 UTC
Labels: duplicate
