### ISSUE TITLE
Nether dimension does not have a different air.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#368] opened 2017-08-22 10:06 UTC
As you seen in screenshot preview from latest update, it does not have and special air, in Nether dimension, must be have different air, same air but it glows, instead of completely dark. Almost same thing as in End dimension, but it shows chunk boundaries if you set it up fancy lighting dynamic.
![screenshot_20170822_125941](https://user-images.githubusercontent.com/13905392/29560368-7edb80f2-873a-11e7-9f7a-02b336bb2116.png)
No chorus fruit or end city and ship to spawn shulkers.
I'm not sure if you get inside of non-solid block to block a lighting, will make a dark?

**Comment by WSDguy2014** [comment] 2017-08-22 10:09
So i test it out and sure enough, it removes special air, if you break it, it won't turn back to special air.

**Comment by Wuzzy2** [comment] 2017-08-22 12:39
I do not like to add any special air. First, it is just redundant, and the complexity will just blow up because a lot in Minetest and MCL2 depends on the built-in air node and I have to basically rewrite a ton of checks to include the “glowing” air as well.
Removing a node also always leaves air behind by default. I would have to overwrite the digging code as well to make sure it uses the special air, not the normal one.
Long story short, the MCL2 code would quickly degrade into an unholy mess, I don't want this.

So, there will be no special air. What I actually need is a way to ensure a minimum light level for all nodes in order to have this “ambient light” effect.

(The End is of course still very WIP and very awful indeed. Note that shulkers *do* spawn. On end stone, actually. But you can also craft shulker shells at the moment (but it is very expensive). These are temporary solutions which will be removed later, of course.)

I close this issue as invalid because not having a glowing air is not a bug. I will soon post another related issue.

**Closed by Wuzzy2** 2017-08-22 12:39 UTC
Labels: invalid
