### ISSUE TITLE
Error after placing chest

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#220] opened 2017-06-07 01:39 UTC
I built a chest and when I try to move stuff to it I get an error (this is unrelated to the pathfinder issue, since there were no pathfinder messages when this happened):

```
2017-06-06 20:34:32: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:-65,15,-34" doesn't exist
2017-06-06 20:34:32: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:-65,15,-34" doesn't exist
2017-06-06 20:34:32: ERROR[Main]: InventoryMenu: The selected inventory location "nodemeta:-65,15,-34" doesn't exist
2017-06-06 20:34:32: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:-65,15,-34" doesn't exist
2017-06-06 20:34:32: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:-65,15,-34" doesn't exist
```

It just repeats that over and over.

**Comment by Wuzzy2** [comment] 2017-06-07 12:43
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/162.

In the meanwhile, try to place the chest somewhere else or place it again. I know, it sucks. I really should fix this bug. :D

**Closed by Wuzzy2** 2017-06-07 12:43 UTC
Labels: duplicate
