### ISSUE TITLE
Mob footstep sounds (snow) can be heard from far away

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#424] opened 2017-11-06 14:37 UTC
Very annoying bug, the footstep sounds (esp. snow) of mobs can be heard from far away.

**Comment by WSDguy2014** [comment] 2017-11-08 18:39
Possibly a duplicate of #346?

**Comment by Wuzzy2** [comment] 2017-11-12 04:56
I know the problem now.
The sound files are stereo sounds. If the files are converted to mono, it works again.

What a silly bug …

https://github.com/minetest/minetest/issues/6615

**Closed** 2017-11-12 05:08 UTC
Labels: annoying, bug, HIGH PRIORITY, sounds
