### ISSUE TITLE
Forgot to add my cradits

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#363] opened 2017-08-07 21:51 UTC
@Wuzzy2 you forgot to add my credit for fixing the uv mapping on some of @22i s models ;)

**Comment by Wuzzy2** [comment] 2017-08-08 01:43
Which ones, specifically? Post in the `mobs_mc` repository if it is about mobs.

**Comment by tobyplowy** [comment] 2017-08-08 11:16
@Wuzzy2 sorry I meant to say you fort to add my credits to this page http://repo.or.cz/MineClone/MineClone2.git

**Comment by Wuzzy2** [comment] 2017-08-08 12:10
And what did you change, specifically?
Please give me file names.

**Comment by tobyplowy** [comment] 2017-08-08 12:15
@Wuzzy2 i fixed the mapping on some models (some faces had mirrored mapping and some faces had the wrong mapping) also don't Remember exactly What Models i fixed or How many but I did a couple at least 8 or so models were fixed ask @22i he may know what models I fixed

**Comment by Wuzzy2** [comment] 2017-08-08 12:43
I wait for 22i to reply.

In the meanwhile, point me to a *single* file you fixed.

---
@22i.

**Comment by tobyplowy** [comment] 2017-08-08 12:54
@Wuzzy2 here you go :)
These I'm sure I fixed
https://github.com/22i/minecraft-voxel-blender-models/blob/master/models/blaze.blend
https://github.com/22i/minecraft-voxel-blender-models/blob/master/models/chicken.blend
https://github.com/22i/minecraft-voxel-blender-models/blob/master/models/ghast.blend
I also changed the sign model but I can't find it anymore for some reason :/

These I'm not sure but I think I did
https://github.com/22i/minecraft-voxel-blender-models/blob/master/models/bat.blend
https://github.com/22i/minecraft-voxel-blender-models/blob/master/models/iron_golem.blend

**Comment by Wuzzy2** [comment] 2017-08-08 16:50
I just checked and I can confirm you are indeed a co-author. I will add you to the credits ASAP.
I think you should also complain to 22i to credit you in these repos:

* https://github.com/22i/minecraft-voxel-blender-models/
* https://github.com/22i/amc

Also complain in `mobs_mc`:
* https://github.com/maikerumine/mobs_mc

**Comment by Wuzzy2** [comment] 2017-08-08 16:52
Fixed in commit 40d3f5c0e67b4744fc28ada34defffc6c1c83fa3.

**Closed by Wuzzy2** 2017-08-08 16:52 UTC

**Comment by tobyplowy** [comment] 2017-08-08 16:54
@Wuzzy2 thanks for your time and effort :)

**Comment by tobyplowy** [comment] 2017-08-08 16:58
@Wuzzy2 also he already did add my credits :)

**Comment by 22i** [comment] 2017-08-11 06:54
tobyplowy also showed how to make better transparent planes better - backface culling - being able to see from outside and inside - being able to see a plane from front and back https://github.com/22i/minecraft-voxel-blender-models/issues/1#issuecomment-279043929

this helped with enderdragon wings, bat wings, chicken legs, mooshroom shrooms, enderman head all villagers, illagers coats, guardians tail, horses tail, silverfish hair, skeletons bones, vex wings, zombie head

**Comment by Wuzzy2** [comment] 2017-08-11 13:40
If you add this info into `mobs_mc` it will eventually end up in MCL2 because I regularily update the mod.
