### ISSUE TITLE
hay bale reduces fall damage too much

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#409] opened 2017-09-26 17:34 UTC
I fell from 100 blocks and didn't take damage.

> An unarmored player with full health and no effects can fall as far as 100.27 blocks onto a hay bale, and still survive with 1 health remaining.

**Comment by Wuzzy2** [comment] 2017-10-02 12:05
The hay bale reduced the percentage correctly. What's wrong is the fall damage model in general. Fall damage in MC is quite different.

Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/126.

**Closed by Wuzzy2** 2017-10-02 12:05 UTC
Labels: duplicate
