### ISSUE TITLE
Glasfiltering

### ISSUE THREAD

**Issue by RonnyBarthmann** [Wuzzy2/MineClone2-Bugs#422] opened 2017-11-04 18:02 UTC
Glas in differents colors not filtering the light
![scr](https://user-images.githubusercontent.com/32592152/32408338-7d813abc-c196-11e7-93f3-a49aa18f85f5.png)

**Comment by Wuzzy2** [comment] 2017-11-05 02:01
Hmm. What is the *exact* expected behaviour?

Do you mean the light level is supposed to drops as soon the sunlight passes through?

According to Minecraft Wiki:

> Glass is a decorative fully transparent block

So I am inclined to close this issues as intended behaviour, but if it turns out that stained glass behaves differently in MC than (unstained glass), this issue is valid.

**Comment by RonnyBarthmann** [comment] 2017-11-05 09:24
my idea is that the glass also colors the light
but I noticed myself that MineTest does not support a colored light
Therefore, was a good idea of mine, but you can reject

**Comment by Wuzzy2** [comment] 2017-11-05 19:14
Sorry, this is too overkill. I won't think about this until Minetest supports colored light.

**Closed by Wuzzy2** 2017-11-05 19:14 UTC
Labels: invalid
