### ISSUE TITLE
Stems on Pumpkins are upside-down

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#143] opened 2017-03-09 01:28 UTC
When growing pumpkins, the stems are upside down when a pumpkin has grown. See screenshot below.
Stems usually are fine when pumpkins are harvested, but not always.

![screenshot_20170308_192628](https://cloud.githubusercontent.com/assets/3247032/23731817/3e34baec-0435-11e7-9daa-e805ce1a9c74.png)

Last tested on 34a531062b54e3de7a8884b202d267b69206caec

**Comment by kwadroke** [comment] 2017-03-09 01:30
Example of harvested pumpkin stem still upside-down
![screenshot_20170308_193000](https://cloud.githubusercontent.com/assets/3247032/23731881/acb84f2e-0435-11e7-9d34-4c46d3671e56.png)

**Comment by Wuzzy2** [comment] 2017-03-09 01:48
Yes.

**Comment by Wuzzy2** [comment] 2017-03-13 19:03
Pumpkin and melon stems are no longer upside down.

But harvesting pumpkins or melons still sometimes does not update the stems.

**Comment by kwadroke** [comment] 2017-03-13 19:06
Will test tonight.

**Comment by Wuzzy2** [comment] 2017-03-13 19:12
Thx. What I want to know is the exact formation of blocks when this happens. For example:

   .P
   .S

I want to know the formation *before* and *after* digging a pumpkin, so I can reproduce it. More screenshots would help a lot.

**Comment by kwadroke** [comment] 2017-03-14 03:08
Screenshots before pulling the fixes

![screenshot_20170313_215924](https://cloud.githubusercontent.com/assets/3247032/23884227/85190014-0839-11e7-88a2-19520f79b46e.png)
![screenshot_20170313_215907](https://cloud.githubusercontent.com/assets/3247032/23884228/85197f9e-0839-11e7-97f5-fc454c8e06f9.png)
![screenshot_20170313_215859](https://cloud.githubusercontent.com/assets/3247032/23884226/85182c20-0839-11e7-9c19-f4d8bdb64c1c.png)
![screenshot_20170313_215846](https://cloud.githubusercontent.com/assets/3247032/23884230/851a27dc-0839-11e7-92bd-93d87f4c1d13.png)
![screenshot_20170313_215834](https://cloud.githubusercontent.com/assets/3247032/23884229/851a0e6e-0839-11e7-9f71-1f8d83afa665.png)

**Comment by kwadroke** [comment] 2017-03-14 03:11
Screenshot after pulling
db123b3d161a3a9a81949f61d7bff7cef1194594

![screenshot_20170313_220042](https://cloud.githubusercontent.com/assets/3247032/23884284/c0fa6244-0839-11e7-9cd4-52ac34e39d21.png)

![screenshot_20170313_220031](https://cloud.githubusercontent.com/assets/3247032/23884288/c8714682-0839-11e7-95f5-bb5f55fcb0d3.png)



Still an issue with some stems

![screenshot_20170313_220038](https://cloud.githubusercontent.com/assets/3247032/23884297/dbdd7b32-0839-11e7-9830-6eb6aa78d3ca.png)


Let me know if you need any more screenshots

**Comment by Wuzzy2** [comment] 2017-03-14 03:35
How did you manage to get that stem that way?

**Comment by kwadroke** [comment] 2017-03-14 03:38
Not exactly sure. It's been that way for a while now. Might have had one grow the right way at one time and produce a pumpkin. It never straightened out. Had another do it not too long ago before I got a runtime error.

![minetest 0 4 15 main menu _004](https://cloud.githubusercontent.com/assets/3247032/23884906/c5f38f10-083d-11e7-81b4-f998ebca0211.png)

I can file a new issue, if you'd like.

**Comment by Wuzzy2** [comment] 2017-03-14 03:40
Lol, you caught me in the middle of heavily working on pumpkins and stems. Naturally, I was not finished at that point. Try to update once again. Sorry for the confusion. :D

**Comment by kwadroke** [comment] 2017-03-14 03:50
No problem. I have a script that tries to pull new commits from your repo when I start Minetest.

Looks like there's been some additions as I haven't seen it do this before: 
![screenshot_20170313_224723](https://cloud.githubusercontent.com/assets/3247032/23885123/44216a32-083f-11e7-89df-7d4b8aaf848a.png)

I've seen it in MineCraft, just not in MineClone2

**Comment by Wuzzy2** [comment] 2017-03-14 04:00
Yes, this was done precisely because of Minecraft. I think the rationale here is to force stems to only be able to grow a new stem when there is not already a pumpkin in any of the 4 directions.

The original issue is fixed, the other one probably, too. I'm closing this now. You may still find bad stems in your existing world, but these may be just a leftovers which would be too much of a hassle to fix. You can fix such leftovers either by removing the stem or by placing and removing a pumpkin to its pointing direction.

If you happen to find any *NEW* bad pumpkin or melon stems, you can file a new issue.

**Closed by Wuzzy2** 2017-03-14 04:00 UTC
Labels: bug, nodes

**Comment by kwadroke** [comment] 2017-03-14 04:05
They're probably just leftovers like you say. I just left them in for bug testing.
