### ISSUE TITLE
Chat Commands

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#289] opened 2017-06-17 18:55 UTC
Time Set Day
Set Spawnpoint
/spawnpoint

**Comment by WSDguy2014** [comment] 2017-06-18 07:26
How about /fill command, that will be useful for creative builders.

**Comment by Gerold55** [comment] 2017-06-18 08:25
Also is it possible 2 map a key button to be able 2 select a block or shift click 2 pick a block?

**Comment by Wuzzy2** [comment] 2017-06-18 15:16
Duplicate of #32.

**Closed by Wuzzy2** 2017-06-18 15:16 UTC
Labels: duplicate
