### ISSUE TITLE
paintings look weird

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#283] opened 2017-06-14 18:56 UTC
![screenshot_20170614_205448](https://user-images.githubusercontent.com/29333817/27149401-b8a9b6dc-5143-11e7-8982-c80584b4c410.png)
this should be a 1x2 painting but is stretched to 3x3
and 1x1 are also stretched to 3x3:
so i made this:
![screenshot_20170614_205353](https://user-images.githubusercontent.com/29333817/27149435-dbea242e-5143-11e7-973f-c5822bde5e2c.png)

**Comment by Wuzzy2** [comment] 2017-06-15 00:25
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/42.

**Closed by Wuzzy2** 2017-06-15 00:25 UTC
Labels: duplicate

**Comment by kingoscargames** [comment] 2017-06-15 08:30
Oh
