### ISSUE TITLE
Inventory location doesn't exist errors when opening new chests

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#165] opened 2017-03-27 00:49 UTC
When placing chests & opening them, I sometimes get the following error:
`2017-03-26 19:45:09: WARNING[Main]: GUIFormSpecMenu::drawList(): The inventory location "nodemeta:42,27,-97" doesn't exist`
These repeat for as long as the chest is open.

If I exit and restart Minetest, I then can use the chest properly. This happens if I make a single chest a double chest or just a single chest.

Using latest commit 277a54a34d7624803ccd7eed9ed23610c05e1414 and Minetest 0.4.15.

**Comment by Bu-Gee** [comment] 2017-03-27 10:16
Is this the same as #162?

**Comment by kwadroke** [comment] 2017-03-27 12:56
Depends. Could be.
Do you need to restart to be able to use the chest? So far I haven't been able to use a chest until I restart Minetest

**Comment by Wuzzy2** [comment] 2017-03-27 15:02
Duplicate of #162.

**Closed by Wuzzy2** 2017-03-27 15:02 UTC
Labels: duplicate
