### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by MarkuBu** [Wuzzy2/MineClone2-Bugs#158] opened 2017-03-19 19:05 UTC
In Minecraft you get fall damage if you fall 4 nodes deep. Minetest default is 6 nodes

> Fall damage is 1 (Half Heart.svg) for each block of fall distance after the third. Thus falling 4 blocks causes 1 (Half Heart.svg) damage, 2 (Heart.svg) damage for 5 blocks, 3 (Heart.svgHalf Heart.svg) for 6 blocks and so forth. Assuming full health (but no Feather Falling or relevant status effects), a 23 block fall should be fatal (23 - 3 = 20 (Heart.svgHeart.svgHeart.svgHeart.svgHeart.svgHeart.svgHeart.svgHeart.svgHeart.svgHeart.svg) of damage), but due to the way fall distance is calculated, a 23.5 block fall is required instead

http://minecraft.gamepedia.com/Damage#Fall_damage

**Comment by Wuzzy2** [comment] 2017-03-19 20:15
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/126.

**Closed by Wuzzy2** 2017-03-19 20:15 UTC
