### ISSUE TITLE
[Importent!] Model mapping

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#43] opened 2017-02-20 10:46 UTC
@Wuzzy2 @22i made some amazing models but some have a copple problems (texture mapping and shape) wuzzy before you add any models for mobs blocks or items can you fist ask me if they are OK (for Quality it would be sad if you add a model and the quality is not correct)

**Comment by Wuzzy2** [comment] 2017-02-20 13:01
Not a bug report. Closing.

PS: Okay. I will only add models for which you requested you added them. But if you're still not happy with a particular model in the repo, you can still edit them and request me to merge this. I'm not afraid to delete low-quality data in favor of better stuff.

Please ask future questions like these in the forums.

**Closed by Wuzzy2** 2017-02-20 13:01 UTC
